import Head from 'next/head'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import { DataSection } from '../components/DataSection'
import { SalesInfoSection } from '../components/SalesSection'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
    <div style={{ width: '100%' }}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'
          integrity='sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=='
          crossorigin='anonymous'
        />
      </Head>

      {/* HEADER   */}
      <Header></Header>

      {/* HERO  */}
      <Hero
        heading={`Build The Community Your Fans Will Love`}
        text={`Huddle re-imagines the way we build communities. You have a voice, but so does
        your audience. Create connections with your users as you engage in genuine discussion.`}
        button={true}
        imgURL={`/images/screen-mockups.svg`}
        altText={`illustration of mockups`}
      ></Hero>

      {/* DATA-SECTION  */}
      <DataSection></DataSection>

      {/* svg data base  */}
      <img
        height='75px'
        width='375px'
        src='/images/bg-section-top-mobile-1.svg'
        alt=''
        className='svg'
      />

      {/* SALES SECTION 1  */}
      <SalesInfoSection
        imgURL='/images/illustration-grow-together.svg'
        altText='illustration of growing together'
        title='Grow Together'
        text='Generate meaningful discussions with your audience and build a strong, loyal community. Think of the insightful conversations you miss out on with a feedback form.'
        bgBlue={true}
      ></SalesInfoSection>

      {/* svg section 1 base  */}
      <img
        height='75px'
        width='375px'
        src='/images/bg-section-bottom-mobile-1.svg'
        alt=''
        className='svg'
      />

      {/* SALES SECTION 2  */}
      <SalesInfoSection
        imgURL='/images/illustration-flowing-conversation.svg'
        altText='illustration of flowing conversation'
        title='Flowing Conversations'
        text="You wouldn't paginate a conversation in real life, so why do it online? Our threads have
        just-in-time loading for a more natural flow."
        bgBlue={false}
      ></SalesInfoSection>

      {/* svg section 3 topper  */}
      <img
        height='75px'
        width='375px'
        src='/images/bg-section-top-mobile-2.svg'
        alt=''
        className='svg'
      />

      {/* SALES SECTION 3  */}
      <SalesInfoSection
        imgURL='/images/illustration-your-users.svg'
        altText='illustration of users'
        title='Your Users'
        text="It takes no time at all to integrate Huddle with your app's authentication solution. This means,
        once signed in to your app, your users can start chatting immediately."
        bgBlue={true}
      ></SalesInfoSection>

      {/* svg section 3 base  */}
      <img
        height='75px'
        width='375px'
        src='/images/bg-section-bottom-mobile-2.svg'
        alt=''
        className='svg'
      />

      <Hero heading={`Ready To Build Your Community?`} button={true}></Hero>

      <div className='empty-box-150'></div>

      {/* footer svg topper  */}
      <img
        height='75px'
        width='375px'
        src='/images/bg-footer-top-mobile.svg'
        alt=''
        className='svg'
      />

      {/* FOOTER SECTION  */}
      <Footer></Footer>

      <footer>
        <p className='ATTRIBUTION'>
          Challenge by{' '}
          <a href='https://www.frontendmentor.io?ref=challenge' target='_blank'>
            Frontend Mentor
          </a>
          . Coded by <a href='#'>Your Name Here</a>.
        </p>
      </footer>
    </div>
  )
}
